services:
  pgvector:
    container_name: agent
    image: 'pgvector/pgvector:pg16'
    environment:
      POSTGRES_DB: agent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - agent_rag_chatbot_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - agent-chatbot-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d agent"]
      interval: 10s
      retries: 5
      start_period: 10s

  keycloak:
    container_name: keycloak-agent
    image: quay.io/keycloak/keycloak:26.1.0
    environment:
      KEYCLOAK_ADMIN: ibrahim
      KEYCLOAK_ADMIN_PASSWORD: 2024
      KC_DB: postgres
      KC_DB_URL_HOST: pgvector
      KC_DB_URL_DATABASE: agent
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: root
    ports:
      - "9090:8080"
    networks:
      - agent-chatbot-net
    depends_on:
      pgvector:
        condition: service_healthy
    command: ["start-dev"]
    restart: unless-stopped

volumes:
  agent_rag_chatbot_data:

networks:
  agent-chatbot-net:
    driver: bridge
